services:
  hans:
    image: kluengels/hans:latest
    restart: always

    expose:
      - 3000

    environment:
      - NEXT_SUPABASE_URL
      - NEXT_SUPABASE_ANON_KEY
      - NEXT_CRYTR_KEY
      - NEXT_PUBLIC_OPENAI_PRICE
      - NEXT_OPENAI_KEY
      - NEXT_EMAIL_HOST
      - NEXT_EMAIL_PORT
      - NEXT_EMAIL_USER
      - NEXT_EMAIL_PASS
      - NEXT_EMAIL_TO

    volumes:
      - tmpfiles:/app/.next/server/app/tmpFiles

volumes:
  tmpfiles: